package com.Book_social_Network.user;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

@Getter // Generates getter methods for all fields.
@Setter // Generates setter methods for all fields.
@Builder // Allows for a builder pattern for creating instances.
@AllArgsConstructor // Generates a constructor with parameters for all fields.
@NoArgsConstructor // Generates a no-arguments constructor.
@Entity// Indicates that this class is a JPA entity.
@EntityListeners(AuditingEntityListener.class)
public class Token {

    @Id // Specifies the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Indicates that the primary key will be generated by the database.
    private Integer id; // Unique identifier for the token.

    private String token; // The actual token string.

    private LocalDateTime expiresAt; // The timestamp when the token expires.

    private LocalDateTime validatedAt; // The timestamp when the token was validated (can be null if not validated).

    private LocalDateTime createdAt; // The timestamp when the token was created.

    @ManyToOne // Defines a many-to-one relationship with the User entity.
    @JoinColumn(name = "user-id", nullable = false) // Specifies the foreign key column in the database.
    private User user; // The user associated with this token.
}
